export const  itemsList = 
    [
       
        // {id:5,title:'Fogg ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368187/analog-digital-skmei-original-imaftkhgzx3zpyvq_sgm2pq.jpg",
        // price:900},
        // {id:6,title:'Fogg Blue',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368188/lcs-8075-lois-caron-original-imafpadkfuyayxd3_gqvdun.jpg",
        // price:860},
        // {id:7,title:'Blue Fogg',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368188/7013-fogg-original-imafmjnfgxpwmg7q_y6cqmi.jpg",
        // price:250},
        // {id:8,title:'Timex ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368187/tw00zr347-timex-original-imafva9zqe6m4x2t_ivsick.jpg",
        // price:1160},
        // {id:9,title:'Timex TW0T',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368187/1170-bl-br-fogg-original-imafdv97yfsrn9wt_wmte10.jpg",
        // price:240},
        // {id:10,title:'Timex Analog',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368187/ls2842-limestone-original-imafjhy58uac48gy_wzsp72.jpg",
        // price:220},
        // {id:11,title:'urad gota',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368865/500-urad-gota-urad-gota-safe-harvest-original-imaff5rvhjrjpx9k_sd3ptv.jpg",
        // price:900},
        // {id:12,title:'mug dal',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368865/500-toor-dal-toor-dal-tata-sampann-original-imafbhqndgfqbknp_ungtue.jpg",
        // price:860},
        // {id:13,title:'delight health ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368864/400-vanilla-delight-health-drink-plastic-bottle-pediasure-original-imaftf97zsdy9wqw_jxqy1p.jpg",
        // price:250},
        // {id:14,title:'Timex ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368864/500-mung-dal-moong-dal-safe-harvest-original-imaff5ruzs9hckbz_yrgiu3.jpg",
        // price:1160},
        // {id:15,title:'Timex ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368864/100-100-natural-california-pouch-happilo-original-imafcgnkxtnghcec_hs5mmd.jpg",
        // price:240},
        // {id:16,title:'Timex ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603368864/1-chana-dal-chana-dal-tata-sampann-original-imaf6svufyt6stbj_cz0mjv.jpg",
        // price:220},
        // {id:17,title:'delight health ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376447/4_n1bavw.jpg",
        // price:250},
        // {id:18,title:'Timex ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376447/3_rq7wgf.jpg",
        // price:1160},
        // {id:19,title:'Timex ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376447/1_apu7oi.jpg",
        // price:240},
        // {id:20,title:'Timex ',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376447/2_obngcf.jpg",
        // price:220},
        //  {id:1,title:'Winter body',size:'lg',imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376766/8_c9le5g.jpg",
        //  desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", price:110},
        // {id:2,title:'Adidas',size:'md', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376766/6_dzvunq.jpg",
        // price:80},
        // {id:3,title:'Vans',size:'lg', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.",
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376766/7_wzi7re.jpg",
        // price:120},
        // {id:4,title:'White',size:'sm', desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima, ex.", 
        // imageUrl:"https://res.cloudinary.com/dvfpkko1z/image/upload/v1603376766/5_nig9fc.jpg",
        // price:260},
       
      ]
